### PR TITLE
Use single rect element for the background

### PR DESCRIPTION
**Pull request by ku1ik**
Thanks again for adding the background color support!

I looked into the code (in order to add the optional 1-cell padding) and realized you render the background using separate rects, just like the foreground ones. I thought it would be simpler and more efficient (size-wise) to render a single background rect covering the whole image. This PR is the result of it. 

This makes the SVG output almost 50% smaller when using background.

Let me know if you'd like to tweak anything. Also, feel free to close if not interested!

### CODE REVIEW

**Comment by waseigo** [comment]
Hello, thank you for the PR! Since the background rect overlaps with the filled-in rects, will that not lead to the colors of the foreground and background rectangles clashing, when opacity is set lower than 1.0?

I'll see if I it's possible to take all the regions of contiguous background rects and turn them into a path by using their external hulls' node coordinates.

**Comment by ku1ik** [comment]
Oh, I didn't get the opacity into account here, so this solution indeed won't work universally... I don't intend to use opacity other than 1.0 and can't really see a use case for it, so I missed this aspect completely.

Using a path may be the way to go, it would be slightly more complicated. I didn't want to inflict extra work on you, and I sent this PR because it seemed like a small change with a nice impact on the output size. The current size of the SVG is still quite small, definitely better than if PNG was used, so I'm fine with closing this and forgetting about it.

**Comment by waseigo** [comment]
No worries -- I'm refactoring this now to make it easier to extract two sets of nodes: one for the foreground squares, and one for the background, including padding. Then, I will see how to convert the contiguous regions of squares into paths. This way we'll get 1) padding, 2) maintain opacity of the overall image across both the fg and bg regions, 3) fewer characters in the inline SVG code, as we get rid of all the repetition of rects. Thanks for the impulse and the interest!

**Comment by ku1ik** [comment]
I think I have another idea for the background vs opacity problem: SVG allows setting `opacity` attr on the root `<svg>` element, making the whole thing use the same opacity. With that you can use a single rect for the background (as I did in this PR) and drop the `opacity` attr from individual foreground rects. If this works then it would not require any special set for background nodes, nor use of paths etc.

**Comment by ku1ik** [comment]
Closing since this doesn't work for opacity, and you already have another idea for this.

**Pull request closed without merging**
